baseurl = "http://eydis.co.uk"
languageCode = "en-us"
title = "Eydis Bjornsdottir"
titleproject = "The Little Child"
[params]
    project_name = "The Little Child"
    project_url = "http://eydis.co.uk"
    project_documentation = "http://eydis.co.uk/content/isl"
    description = "Enjoy life and be happy!"
    author_url = "http://eydis.co.uk"

    first_color="#f2f0ab"
    first_border_color="#e7e7e7"
    first_text_color="#491d1d"

    second_color="white"
    second_text_color="#491d1d"

    header_color="#f8f8f8"
    header_text_color="rgb(73, 29, 29)"

    header_link_color="#777"
    header_link_hover_color="rgb(73, 29, 29)"


