baseurl = "http://eydis.co.uk/is"
languageCode = "en-us"
title = "Eydís Björnsdóttir"
titleproject = "Bækur"
[params]
    project_name = "Ýmsar barnabækur"
    project_url = "http://eydis.co.uk/is"
    description = "Safn af nokkrum bókum"
    project_documentation ="/#buy"
    author_url = "/#about"


    first_color="#f2f0ab"
    first_border_color="#e7e7e7"
    first_text_color="#491d1d"

    second_color="white"
    second_text_color="#491d1d"

    header_color="#f8f8f8"
    header_text_color="rgb(73, 29, 29)"

    header_link_color="#777"
    header_link_hover_color="rgb(73, 29, 29)"

    googleAnalytics ="UA-74406852-1"
