# Page settings

baseURL = "https://www.eydis.co.uk/is/"
languageCode = "en"
title = "Engin útgáfa"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-74406852-1"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Engin útgáfa"
        tagline = "Barnabækur"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = ""

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "eydis@eydis.co.uk"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "http://www.facebook.com/enginutgafa"
        text = "Facebook síða"







    [params.skills]
        enable = false

        [[params.skills.list]]
        title = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""

        [[params.skills.list]]
        title = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""








    [params.education]
        enable = true

        [[params.education.list]]
        degree = ""
        university = ""
        dates = ""
        [[params.education.list]]
        degree = ""
        university = ""
        dates = ""








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = ""
        body = ""
        date = ""
        [[params.awards.list]]
        name = ""
        body = ""
        date = ""








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = ""
        level = ""
        [[params.languages.list]]
        name = ""
        level = ""








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = ""
        [[params.interests.list]]
        name = ""
        [[params.interests.list]]
        name = ""
        [[params.interests.list]]
        name = ""








    [params.summary]
        enable = true
        text = "Hér eru tvær barnabækur sem hægt er að lesa og hlaða niður ókeypis."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Láta mér líða vel?"
        dates = ""
        company = ""
        details = "Væri lífið ekki betra ef allir væru glaðir með sig og sitt? Svo glaðir að það væri ekki þörf fyrir öfund eða eigingirni? En þetta getur stundum bara verið ansi snúið. Bók fyrir þessar stundir þegar okkur tekst ekki að vera góð við aðra. Og þegar við erum ekki góð við okkur sjálf. Bók sem minnir okkur á mikilvægi þess að líða vel."
        [[params.experience.list.items]]
        details = "Bókin er ekki lengur með Dyslexia leturgerðina sem auðveldar lesblindum lesturinn. Hún er nú með letri sem heitir Chelsea Market. Það fylgir Open Font License og er fáanlegt á Google Fonts. Ég þurfti að gera þessa breytingu til að geta boðið bókina ókeypis."
        [[params.experience.list.items]]
        details = "Hægt er að hlaða niður pdf skjalinu hér eða lesa bókina á issuu."



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Jólaþjóðsaga úr samtímanum"
        meta = ""
        tagline = "Heimilin eru í hættu og það er enginn til staðar til að bjarga þeim. Nema jólasveinarnir. En það eru allir hættir að trúa á þá, meira að segja þeir sjálfir. Hvað geta þeir þá gert? Jólasveinarnir tilheyra löngu liðnum tíma. Þeir tilheyra sveitinni, bóndabænum og baðstofunni. Askasleikir sem dæmi stelur matarleifum úr askinum. Hvaða barn snæðir daglega úr ask í dag? En hvað ef það væru til nútímalegri jólasveinar? Sveinar sem ásælast hluti sem standa okkur nær? Og hvernir sveinar yrðu það? Gæfu þeir í skóinn? Eða væru þeir meiri ógn, fyrst þeir ásælast jú það sama og við? Og hvernig myndu svo gömlu jólasveinarnir bregðast við svona stökkbreyttum aðskotahlutum? Fjölskylduvæn saga fyrir börn á aldrinum 8 - 12 ára, eða um þann aldur sem þau eru hætt að trúa."







    [params.information]
        enable = false

        [[params.information.list]]
        title = ""
        [[params.information.list.items]]
        details = ""
        [[params.information.list.items]]
        details = ""

        [[params.information.list]]
        title = ""
        details = ""








    [params.social]
        enable = false

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"
