baseurl = "http://www.eydis.co.uk/is/"
languageCode = "en-us"
title = "Eydís"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-74406852-1"

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	logo = "/images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	email   = "eydis@eydis.co.uk"


[[menu.main]]
	name   = "/ Bækurnar"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Engill og Þengill"
	url    = "engill-og-thengill/"
	weight = 10

[[menu.main]]
	name   = "Litla barnið"
	url    = "litla-barnid/"
	weight = 20

[[menu.main]]
	name   = "Jeremías"
	url    = "jeremias/"
	weight = 30

[[menu.main]]
	name   = "Þegar jólasveinarnir"
	url    = "jolasveinarnir/"
	weight = 40



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
